openapi: 3.0.0
info:
  title: Asesorías API
  description: API para gestionar el sistema de asesorías universitarias
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Servidor local

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

tags:
  - name: Careers
    description: Rutas de carreras
  - name: Users
    description: Rutas de usuarios
  - name: Advisory
    description: Rutas de asesorías
  - name: Schedule
    description: Rutas de agendamiento de asesorías
security:
  - ApiKeyAuth: []
paths:
  /career/create:
    post:
      summary: Crear una nueva carrera
      tags:
        - Careers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Ingeniería de Sistemas"
                code:
                  type: string
                  example: "115"
      responses:
        "201":
          description: Carrera creada con éxito
        "400":
          description: Datos inválidos
        "500":
          description: Error interno del servidor
  /career/:
    get:
      summary: Obtener todas las carreras
      tags:
        - Careers
      responses:
        "201":
          description: Carreras obtenidas
  /user/register:
    post:
      summary: Crear un nuevo usuario
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Juan Pérez"
                email:
                  type: string
                  example: "juan.perez@example.com"
                password:
                  type: string
                  format: password
                  example: "123456"
                role:
                  type: string
                  enum: ["student", "professor"]
                  example: "student"
                career:
                  type: string
                  description: "ID de la carrera a la que pertenece"
                  example: "67d3b319b244114e7e12ef17"
                codigo:
                  type: string
                  description: "Código del estudiante o profesor"
                  example: "1151756"
      responses:
        "201":
          description: Usuario registrado con éxito
        "400":
          description: Datos inválidos
        "500":
          description: Error interno del servidor
  /user/login:
    post:
      summary: Iniciar sesión
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: "usuario@example.com"
              password: "123456"
      responses:
        "200":
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsIn..."
        "400":
          description: Credenciales inválidas
        "500":
          description: Error interno del servidor
  /advisory:
    get:
      summary: Obtener todas las asesorías
      tags: 
        - Advisory
      responses:
        '200':
          description: Lista de asesorías

  /advisory/create:
    post:
      summary: Crear una nueva asesoría
      tags: 
        - Advisory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                advisorId:
                  type: string
                  description: ID del asesor asignado
                  example: 123
                careerId:
                  type: string
                  description: ID de la materia
                  example: 456
                dateStart:
                  type: string
                  format: date-time
                  description: Fecha y hora de inicio
                status:
                  type: string
                  enum: [pending, approved, completed, canceled]
                  description: Estado de la asesoría
                  example: pending
      responses:
        '201':
          description: Asesoría creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/advisory'
        '400':
          description: Datos inválidos
  /advisory/{advisoryId}:
    get:
      summary: Obtener una asesoría por ID
      tags: 
        - Advisory
      parameters:
        - name: advisoryId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalles de la asesoría
        '404':
          description: Asesoría no encontrada
    put:
      summary: Actualizar una asesoría
      tags: 
        - Advisory
      parameters:
        - name: advisoryId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                advisoryId:
                  type: string
                  description: ID del amigo academico
                  example: 67d4df40e1711993d1edd37f
                careerId:
                  type: string
                  description: ID de la materia
                  example: 67d3b319b244114e7e12ef17
                dateStart:
                  type: string
                  format: date-time
                  description: Fecha y hora de inicio
                status:
                  type: string
                  enum: [pending, confirmed, completed, canceled]
                  description: Estado actualizado de la asesoría
                  example: pending

      responses:
        '200':
          description: Asesoría actualizada correctamente
        '400':
          description: Datos inválidos
        '404':
          description: Asesoría no encontrada
    delete:
      summary: Eliminar una asesoría
      tags: 
        - Advisory
      parameters:
        - name: advisoryId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Asesoría eliminada correctamente
        '404':
          description: Asesoría no encontrada
 
  /schedules/create:
    post:
      summary: Crear un nuevo registro de asistencia agendada
      tags:
        - Schedule
      requestBody:
        required: true
        content:
          application/json:
            schema:
            example:
              "studentId": "67d4df03e1711993d1edd37b"
              "topic": "Introducción a la Programación"
              "advisoryId": "67d8d485dc4bf243ae06a1fc"
              "status": "pending"
      responses:
        201:
          description: Registro de asistencia agendada creado exitosamente
  /schedules/{scheduleId}:
    get:
      summary: Obtener un registro de asistencia agendada por ID
      tags:
        - Schedule
      parameters:
        - name: scheduleId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Registro de asistencia obtenido exitosamente
    put:
      summary: Actualizar un registro de asistencia agendada
      tags:
        - Schedule
      parameters:
        - name: scheduleId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schedule'
      responses:
        200:
          description: Registro actualizado exitosamente
    delete:
      summary: Eliminar un registro de asistencia agendada
      tags:
        - Schedule
      parameters:
        - name: scheduleId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Registro eliminado exitosamente
  /advisory/report/last7days:
    get:
      summary: Obtener el reporte de asesorías de los últimos 7 días
      tags:
        - Advisory
      responses:
        "200":
          description: Informe de asesorías agrupadas por día

  /advisory/report/last30days:
    get:
      summary: Obtener el reporte de asesorías de los últimos 30 días
      tags:
        - Advisory
      responses:
        "200":
          description: Informe de asesorías agrupadas por día
          

  /advisory/report/lastyear:
    get:
      summary: Obtener el reporte de asesorías de cada mes en el último año
      tags:
        - Advisory
      responses:
        "200":
          description: Informe de asesorías agrupadas por mes


  /advisory/report/bydaterange:
    get:
      summary: Obtener el reporte de asesorías en un rango de fechas específico
      tags:
        - Advisory
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Fecha de inicio en formato YYYY-MM-DD
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Fecha de finalización en formato YYYY-MM-DD
      responses:
        "200":
          description: Informe de asesorías dentro del rango de fechas

  /advisory/report/mostActiveAdvisor:
    get:
      summary: Obtener el asesor con más asesorías asignadas
      tags:
        - Advisory
      responses:
        "200":
          description: Información del asesor más solicitado, incluyendo nombre, topic y carrera.

  /advisory/reports/yearly:
    get:
      summary: Obtener reporte de asesorías por año
      tags:
        - Advisory
      parameters:
        - name: year
          in: query
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Reporte de asesorías anuales

  /advisory/report/top-careers:
    get:
      summary: Obtener las 5 carreras con más asesorías
      tags:
        - Advisory
      responses:
        "200":
          description: Retorna las carreras con más asesorías
