openapi: 3.0.0
info:
  title: Asesorías API
  description: API para gestionar el sistema de asesorías universitarias
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Servidor local

tags:
  - name: Careers
    description: Rutas de carreras
  - name: Users
    description: Rutas de usuarios
  - name: Advisory
    description: Rutas de asesorías

paths:
  /career/create:
    post:
      summary: Crear una nueva carrera
      tags:
        - Careers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Career'
      responses:
        "201":
          description: Carrera creada con éxito
        "400":
          description: Datos inválidos
        "500":
          description: Error interno del servidor
  /career/:
    get:
      summary: Obtener todas las carreras
      tags:
        - Careers
      responses:
        "201":
          description: Carreras obtenidas
  /user/register:
    post:
      summary: Crear un nuevo usuario
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "201":
          description: Usuario registrado con éxito
        "400":
          description: Datos inválidos
        "500":
          description: Error interno del servidor
  /user/login:
    post:
      summary: Iniciar sesión
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        "200":
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsIn..."
                  user:
                    $ref: '#/components/schemas/User'
        "400":
          description: Credenciales inválidas
        "500":
          description: Error interno del servidor
  /advisory/create:
    post:
      summary: Crear una asesoría
      tags:
        - Advisory
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Advisory'
      responses:
        '201':
          description: Asesoría creada con éxito
        '400':
          description: Datos inválidos
        '403':
          description: No autorizado
        '500':
          description: Error en el servidor
  /advisory/:
    get:
      summary: Obtener todas las asesorías
      tags:
        - Advisory
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de asesorías obtenida con éxito
        '403':
          description: No autorizado
        '500':
          description: Error en el servidor

  /advisory/{id}:
    get:
      summary: Obtener asesoría por ID
      tags:
        - Advisory
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID de la asesoría
      responses:
        '200':
          description: Asesoría obtenida con éxito
        '404':
          description: Asesoría no encontrada
        '500':
          description: Error en el servidor

    put:
      summary: Actualizar una asesoría
      tags:
        - Advisory
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID de la asesoría a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdvisoryUpdate'
      responses:
        '200':
          description: Asesoría actualizada con éxito
        '404':
          description: Asesoría no encontrada
        '500':
          description: Error en el servidor

    delete:
      summary: Eliminar una asesoría
      tags:
        - Advisory
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID de la asesoría a eliminar
      responses:
        '200':
          description: Asesoría eliminada con éxito
        '404':
          description: Asesoría no encontrada
        '500':
          description: Error en el servidor
  /subjects:
    get:
      summary: Obtener todas las materias
      description: Retorna una lista de todas las materias disponibles en el sistema.
      tags:
        - Subjects
      responses:
        "200":
          description: Lista de materias obtenida exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Subject"
  /subjects/create:
    post:
      summary: Crear una nueva materia
      description: Crea una nueva materia en la base de datos.
      tags:
        - Subjects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubjectInput"
      responses:
        "201":
          description: Materia creada exitosamente.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subject"
        "400":
          description: Error en la solicitud.

  /subjects/{id}:
    get:
      summary: Obtener una materia por ID
      description: Retorna los detalles de una materia específica según su ID.
      tags:
        - Subjects
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID de la materia
      responses:
        "200":
          description: Materia encontrada.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subject"
        "404":
          description: Materia no encontrada.

    put:
      summary: Actualizar una materia
      description: Modifica los datos de una materia existente.
      tags:
        - Subjects
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID de la materia
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubjectInput"
      responses:
        "200":
          description: Materia actualizada exitosamente.
        "400":
          description: Error en la solicitud.
        "404":
          description: Materia no encontrada.

    delete:
      summary: Eliminar una materia
      description: Elimina una materia de la base de datos.
      tags:
        - Subjects
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID de la materia
      responses:
        "200":
          description: Materia eliminada exitosamente.
        "404":
          description: Materia no encontrada.
components:
  schemas:
    Career:
      type: object
      properties:
        name:
          type: string
          example: "Ingeniería de Sistemas"
        code:
          type: string
          example: "115"

    User:
      type: object
      properties:
        name:
          type: string
          example: "Juan Pérez"
        email:
          type: string
          example: "juan.perez@example.com"
        password:
          type: string
          format: password
          example: "123456"
        role:
          type: string
          enum: ["student", "professor"]
          example: "student"
        career:
          type: string
          description: "ID de la carrera a la que pertenece"
          example: "67d3b319b244114e7e12ef17"
        codigo:
          type: string
          description: "Código del estudiante o profesor"
          example: "1151756"
    Login:
      type: object
      properties:
        email:
          type: string
          example: "juan.perez@example.com"
        password:
          type: string
          format: password
          example: "123456"
    Advisory:
      type: object
      properties:
        academicFriendCode:
          type: string
          description: ID del asesor asignado
        studentCode:
          type: string
          description: ID del estudiante que solicita la asesoría
        subjectCode:
          type: string
          description: Materia de la asesoría
        topic:
          type: string
          description: Tema de la asesoría
        date:
          type: string
          format: date-time
          description: Fecha de la asesoría
        status:
          type: string
          enum: [pending, confirmed, completed, canceled]
          description: Estado de la asesoría

    AdvisoryUpdate:
      type: object
      properties:
        status:
          type: string
          enum: [pending, confirmed, completed, canceled]
          description: Estado actualizado de la asesoría
    Subject:
      type: object
      properties:
        id:
          type: string
          description: ID único de la materia.
        name:
          type: string
          description: Nombre de la materia.
        careerCode:
          type: string
          description: ID de la carrera asociada a la materia.
      example:
        id: "60f7c0e4a4b5a814d89b2a5d"
        name: "Programación Avanzada"
        careerCode: "60f7b1234c8e2f001c9a3b45"

    SubjectInput:
      type: object
      properties:
        name:
          type: string
          description: Nombre de la materia.
        careerCode:
          type: string
          description: ID de la carrera asociada a la materia.
      required:
        - name
        - careerCode
      example:
        name: "Matemáticas Discretas"
        careerCode: "60f7b1234c8e2f001c9a3b45"
